name: Upload to Qiniu

on:
  push:
    branches:
      - main  # 或者你想要触发上传的其他分支

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload to Qiniu
        uses: saltbo/uptoc@master
        with:
          driver: qiniu
          region: cn-south-1
          bucket: ${{ secrets.QINIU_BUCKET }}
          exclude: .git,.github,.vscode
          dist: .
        env:
          UPTOC_UPLOADER_AK: ${{ secrets.QINIU_ACCESS_KEY }}
          UPTOC_UPLOADER_SK: ${{ secrets.QINIU_SECRET_KEY }}

      - name: Refresh Qiniu Cache
        run: |
          BODY='{"domains":["https://nav.hrhe.cn"],"urls":[]}'
          PATH="/v2/domains/prefetch"
          HOST="fusion.qiniuapi.com"
          CONTENT_TYPE="application/json"
          DATE=$(date -u "+%a, %d %b %Y %H:%M:%S GMT")
          SIGNED_STRING="POST $PATH\nHost: $HOST\nContent-Type: $CONTENT_TYPE\nDate: $DATE\n\n$BODY"
          SIGNATURE=$(echo -n "$SIGNED_STRING" | openssl dgst -binary -hmac "${{ secrets.QINIU_SECRET_KEY }}" -sha1 | base64 | tr '+/' '-_')
          AUTH="Qiniu ${{ secrets.QINIU_ACCESS_KEY }}:$SIGNATURE"
          
          curl -X POST \
          "https://$HOST$PATH" \
          -H "Content-Type: $CONTENT_TYPE" \
          -H "Date: $DATE" \
          -H "Authorization: $AUTH" \
          -d "$BODY"