name: Upload to Qiniu

on:
  push:
    branches:
      - main  # 或者你想要触发上传的其他分支

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 使用最新版本

      - name: Upload to Qiniu
        uses: saltbo/uptoc@master  # 确保使用正确的版本
        with:
          driver: qiniu
          region: cn-south-1  # 确保区域正确
          bucket: ${{ secrets.QINIU_BUCKET }}
          exclude: .git,.github,.vscode
          dist: .
        env:
          UPTOC_UPLOADER_AK: ${{ secrets.QINIU_ACCESS_KEY }}
          UPTOC_UPLOADER_SK: ${{ secrets.QINIU_SECRET_KEY }}

      - name: Refresh Qiniu CDN cache
        run: |
          npm install qiniu
          node refresh_qiniu_cdn.js
        env:
          QINIU_ACCESS_KEY: ${{ secrets.QINIU_ACCESS_KEY }}
          QINIU_SECRET_KEY: ${{ secrets.QINIU_SECRET_KEY }}
          QINIU_DOMAIN: ${{ secrets.QINIU_DOMAIN }}
          QINIU_URLS: |
            http://${{ secrets.QINIU_DOMAIN }}/
            https://${{ secrets.QINIU_DOMAIN }}/